hostName: dvszhuravskvm01
domainName: ".navimedix.com"
userCredentials:
    defaultUser:
        userName: authuseronyx
        password: 8cambridge
    user2:
        userName: authuseronyx1
        password: 8cambridge